"""empty message

Revision ID: 1795f174e195
Revises: 
Create Date: 2017-04-25 09:06:27.852927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1795f174e195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eroticarticle', sa.Column('url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eroticarticle', 'url')
    # ### end Alembic commands ###
