"""empty message

Revision ID: 201a86082a0f
Revises: 1795f174e195
Create Date: 2017-05-19 00:23:49.206355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201a86082a0f'
down_revision = '1795f174e195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraph', sa.Column('para_idx', sa.Integer(), nullable=True))
    op.add_column('translation', sa.Column('para_idx', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation', 'para_idx')
    op.drop_column('paragraph', 'para_idx')
    # ### end Alembic commands ###
