"""empty message

Revision ID: 844487383a43
Revises: 201a86082a0f
Create Date: 2017-05-21 15:30:33.308645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844487383a43'
down_revision = '201a86082a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eroticarticle', sa.Column('viewcount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eroticarticle', 'viewcount')
    # ### end Alembic commands ###
